name: Test Email Step

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions UI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2004977@ds.study.iitm.ac.in
        run: echo "Hello, world!"
